### PR TITLE
guess-who dockerized; added dockerfile and docker-compose

### PR DESCRIPTION
**Pull request by timchunght**
I dockerized the application and added the Docker deployment step to the Readme. I hope this helps!

Cheers,
Tim

PS. It was nice to meet you at 500 today.

### CODE REVIEW

**Comment by timchunght** [comment]
Ruby version was changed to 2.1.6 because it was the default in the Ubuntu PPA for 2.1.x. It shouldn't introduce any errors.

**Comment by timchunght** [comment]
This commit updated the Dockerfile to matche your newest commits yesterday.

**Comment by cyrusstoller** [comment]
This is awesome :+1:

Can you add a little more detail to the README so people know where to look for info on how to use Docker?

Then I need to switch my deployments to use Docker :smile:

**Comment by cyrusstoller** [comment]
I think I may also add a little bit to the readme on pros and cons of using Capistrano vs Docker.

What's the best way to rollback deployments with Docker? I've never deployed my own projects with Docker. I've only used other people's images.

**Comment by cyrusstoller** [comment]
I merged this after a rebase.  :+1:

**Pull request closed without merging**
